### PR TITLE
Dg 66/implement unit test for calculate score

### PR DESCRIPTION
**Pull request by Gerald-codes**
Total Coverage: 97%

image

### CODE REVIEW

**Comment by Gerald-codes** [comment]
Unnecessary message removed. 

Coverage 97%
image

**Comment by Gerald-codes** [comment]
image

**Comment by JamesYuRenxiang** [comment]
Coverage is 97%, the same as the image attached above.

image

The display of the current score is adjusted correctly.

image
 
Current Score Table

image

Final Score Table

The code has been approved and is ready to be merged to the Integration branch.

**Comment by Linus-Tay** [comment]
It seems to me that the code is ready.

**Pull request merged**
