### PR TITLE
[DG-103] & [DG-107] refracted main.py and city.py based on client's feedback

### PR DESCRIPTION
**Pull request by ZhenAnC**
- Added "Building Settings" in "Main Menu"
- Added sub-menu in "Building Settings"
- removed "[3] View remaining buildings" and updated the menu accordingly based on feedback in #159 
- updated test cases that were affected by the removal of "[3] View remaining buildings"

overall coverage test with all passed at 97%
image

### CODE REVIEW

**Comment by JamesYuRenxiang** [comment]
The coverage is 97%,  the same as mentioned above

image

The developed code has passed all unit tests. 

image

Functions seem to be working fine. However, there are some details to take note of.

image

For example, on the main menu, the option could be named "Settings" instead of "Building Settings" since the settings consists of both changing city size and building pool.

image

The game board with the remaining buildings displayed seems to be fine to me. However, it would be better if there is a gap between the menu and the game board.

image

There should be a gap between the "Option 3 - Building Settings" and the first option in the menu to standardize across the whole game just like Option 1 above and Option 2 below. The option "[0] Return to previous menu" should also have a gap from the option "[2] Choose Building Pool" to standardize as well. The option "[0] Return to previous menu" can also be renamed to "[0] Return to main menu"

image

Could appropriately put spaces in between to make it look more neat and presentable for the users. Options to be in caps like "[1] Re-configure city map" and "[0] Return to previous menu" and option "[0] Return to previous menu" can be "[0] Return to options menu"

Might also wanna put like a sentence to tell them the limit for the city dimensions like "Please note that limit for city dimension is 40 squares and limit for rows is 26." before prompting the user for new city dimension.

image

Might also want to reduce the limit for columns to 20 because although displaying 26 columns for the monitor screen is fine but for laptop screen, it is too much to display together. To cater to the users using laptop screen, might want to reduce it to 20

@ZhenAnC remember to refract these details while developing your next function. Development code is approved and can be merged.

**Comment by Linus-Tay** [comment]
I disagree, I think this pull request should be left open until @ZhenAnC updates and pushes to this request with the finishing touches.

**Comment by ZhenAnC** [comment]
I have worked on @JamesYuRenxiang comments and the changes can be found in my latest commit. 
Also refracted the way default city is loaded to make it more universal so that other functions can use it too.

Overall coverage test passed at 97%
image


 Please do make a check! thank you

**Comment by JamesYuRenxiang** [comment]
The coverage is 97%, the same as mentioned above.

image

The developed code has passed all unit tests.

image

The details mentioned before have been implemented into the code. However, the function seems to have an issue.

image

As you can see here, I have set the new city size to be 1 row and 20 columns.

image

However, when I started a new game, the city size is 20 rows and 1 column.

However, other than that, everything else is fine. Please refract this issue. Thank you @ZhenAnC!

**Comment by ZhenAnC** [comment]
Fixed the issue of city map being reversed mentioned by @JamesYuRenxiang in commit b68f28d038daba34beecb433271a65b1abab948a

please check again thank you!

**Comment by JamesYuRenxiang** [comment]
The coverage is 97%, the same as mentioned above.

image

The developed code has passed all unit tests.

image

The problem previously raised has been resolved. Code is approved and ready to be merged.

**Comment by Linus-Tay** [comment]
Everything seems to be in order. Nice job.

**Pull request merged**
