### PR TITLE
[DG-116] & [DG-117] create feature choose building pool with unit test 

### PR DESCRIPTION
**Pull request by ZhenAnC**
- added choose building pool feature with test cases ("test_buildingPools.py")
- added load default pool using the same logic as loading default city
- update "Main" options menu, "View High Score" is now option3 and "Settings" is now option 4 following tech lead's guide
- added test cases for choosing building pool ("test_main.py")

coverage test all passed at 97%
image

I have identified a list of things to do for next the refract, please help to advise.
Things to do for next refract:

- update error for choose city size accordingly based on QA's comments (Refer to SS below)
- will further clean coverage
- refract "test_Buildings.py" and "Buildings.py" as it may not work according to the new software changes
image

image
image

### CODE REVIEW

**Comment by JamesYuRenxiang** [comment]
The development code has passed all unit tests.

image

Coverage is 97%, the same as mentioned above.

image

The function worked as intended. One minor detail to take note of:

image

Should be "[1] Re-configure building pool" instead of "[1] Re-configure city map"

Pls refract @ZhenAnC

**Comment by JamesYuRenxiang** [comment]
You might want to refract how your buildings are built since the city size is dynamic when we allow the users to change city size @ZhenAnC

**Comment by ZhenAnC** [comment]
@JamesYuRenxiang @Linus-Tay 
Please refer to my latest commits of commit 50f4b85b38073ad6f8ea6188dec2fdae3a6975de and commit 36a1ce1f4a8e5af8439e0fe545cead0416a0e9b9 for the buildings refract.
- added more test cases for buildings
- unit test passed
- did additional manual testing which seems fine too
- all test cases passed with 97% coverage score
image

**Comment by JamesYuRenxiang** [comment]
The development has passed all unit tests.

image

Coverage is 97%, the same as stated above.

image

The features work as expected.

The development code is approved and ready to be merged.

**Comment by Linus-Tay** [comment]
Alright noted, Thank you Zhen An and James.

**Pull request merged**
