### PR TITLE
Dg 100/high score implementation

### PR DESCRIPTION
**Pull request by Gerald-codes**
Merging High Score into Integration 
Total Coverage: 94% 
image

### CODE REVIEW

**Comment by Gerald-codes** [comment]
Total Coverage: 97%
image

**Comment by JamesYuRenxiang** [comment]
The development code has passed all unit tests.

image

Coverage is 97%, the same as mentioned above.

image

Able to view the high score from the main menu option and view other high score tables as well. 

Code is approved and can be merged.

Update: The developers want to refract first, so we shall leave this pull request open as it is till the developer is done refracting.

**Comment by Gerald-codes** [comment]
Resolve merge conflict and total coverage is 97%

image

**Comment by JamesYuRenxiang** [comment]
The development code has passed all unit tests.

image

Coverage is 97%, the same as mentioned above.

image

The game is able to view the high score from the main menu option and view other high score tables as well.

Code is approved and can be merged.

**Comment by Linus-Tay** [comment]
Checked and Reviewed. This was reviewed late as it was coming to the end of the Sprint and we had missed out on this.

**Comment by Linus-Tay** [comment]
Closed accidentally, will merge now to close pull request.

**Pull request merged**
